server:
  port: 8081

spring:
  application:
    name: toolbox
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/toolbox.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true